### ISSUE TITLE
Need help with intellisense in vscode

### ISSUE THREAD

**Issue by sleepingsaint** [yash1200/flutter_battery_linux#1]
I am trying to develop a native code plugin for linux and I came your medium article which really helped me :). 
But when I am trying to edit the code <my module>.cc there are a few include directory not found error, but the code is getting compiled properly. 
![image](https://user-images.githubusercontent.com/35530053/186214132-0884d090-b100-4d7b-8074-0413b6cabc75.png)
I am using vscode for the development, so could you provide any cpp configurations to do to remove those intellisense errors.

Thanks in advance :)

**Comment by yash1200** [comment]
Hey @sleepingsaint ! I remember these intellisense errors used to come in my vscode as well. I don't know how to fix them, ignore these if the code is getting compiled without any errors.
